---
- hosts: all
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
    - name: install pip
      yum:
        name: python-pip
        state: present
